### ISSUE TITLE
SP3-Metodolo de Logeo (Generar, Validar Token)

### ISSUE THREAD

**Issue by Yhor93** [Yhor93/Proyecto-Inmobiliaria#16]

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/200099815-8deda804-42ca-4ac3-8fdb-82a8183cb365.png)

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/200099890-9b1d846d-88c0-4106-8c30-ae3073f46692.png)

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/200099984-215497bb-70d6-405b-83c5-8575c8fa1444.png)
