### ISSUE TITLE
SP3-Creacion Formulario HTML (Registro,Login,Recuperacion Contraseña)

### ISSUE THREAD

**Issue by Yhor93** [Yhor93/Proyecto-Inmobiliaria#17]

**Comment by RojasJhonatan** [comment]
![Image](https://user-images.githubusercontent.com/111137856/200212839-a794756f-b2d6-4a1f-963a-801fb7afdc5f.png)



![Image](https://user-images.githubusercontent.com/111137856/200212890-875ec12c-f7a4-4b20-a8ca-89df9e8ef39b.png)



![Image](https://user-images.githubusercontent.com/111137856/200212789-a247c84c-28d3-46cc-969f-0320e4cf13ec.png)
