### ISSUE TITLE
SP4-Codificacion de los Formularios del Proyecto

### ISSUE THREAD

**Issue by Yhor93** [Yhor93/Proyecto-Inmobiliaria#23]

**Comment by RojasJhonatan** [comment]
![Image](https://user-images.githubusercontent.com/111137856/201542828-73a6339e-8c3e-4f64-88d6-e69592d3ce68.png)



![Image](https://user-images.githubusercontent.com/111137856/201542853-a1da27d2-1800-4af0-bcd1-3ad3caa5ea3b.png)



![Image](https://user-images.githubusercontent.com/111137856/201542885-ea5c7bda-bab6-4fd3-b934-c941693b70f5.png)
