### ISSUE TITLE
SP5-Diseñar Pag Inicio

### ISSUE THREAD

**Issue by Yhor93** [Yhor93/Proyecto-Inmobiliaria#25]

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/202041532-424a590f-5c6c-4014-8ceb-6e04305549df.png)

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/202041889-f93bc9df-d696-431d-a67f-9057adc265fa.png)

**Comment by frozen1000** [comment]
![Image](https://user-images.githubusercontent.com/109002823/202806762-2786b4e6-4710-4389-8a89-c48204ceacbc.png)
![Image](https://user-images.githubusercontent.com/109002823/202806763-795b7ca1-1eae-428c-b1d1-f984ac32a339.png)
![Image](https://user-images.githubusercontent.com/109002823/202806764-8bacd4bd-c312-4e3b-8e7d-992f4be6fa64.png)
