### ISSUE TITLE
SP5-Diseñar Form Registro y su Validacion

### ISSUE THREAD

**Issue by Yhor93** [Yhor93/Proyecto-Inmobiliaria#40]

**Comment by frozen1000** [comment]
Formulario



![Image](https://user-images.githubusercontent.com/111392975/202870417-3564d6c5-725a-4bdc-9dd1-d8aecec0fd16.png)

Validacion Exitosa

![Image](https://user-images.githubusercontent.com/111392975/202870387-05672e1b-c03a-490e-b178-e0148e513ef5.png)

**Comment by frozen1000** [comment]
![Image](https://user-images.githubusercontent.com/111392975/202870467-fa619583-d1e5-443e-828c-80035e17a2e0.png)
