### ISSUE TITLE
SP5- Personalizar Footer

### ISSUE THREAD

**Issue by Yhor93** [Yhor93/Proyecto-Inmobiliaria#41]

**Comment by RojasJhonatan** [comment]
![Image](https://user-images.githubusercontent.com/111137856/202602687-a1d82b7b-7235-4a07-a49c-411818fb094c.png)



![Image](https://user-images.githubusercontent.com/111137856/202602712-9680392b-3c6f-4bc1-b043-08c175fd80a7.png)
