### ISSUE TITLE
SP2-Generar Servidor (Correo Electronico)

### ISSUE THREAD

**Issue by Yhor93** [Yhor93/Proyecto-Inmobiliaria#5]

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/198795341-80ebfbf0-3889-4f6e-a836-bdc4b771aeda.png)

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/198796412-15fd1513-cea4-434a-88aa-8d0c1246cf58.png)

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/198800650-c027e503-a840-49b1-85e1-02d210683cba.png)

**Comment by ramisistemas** [comment]
COMANDOS UTILIZADOS

conda install -c  conda-forge twilio
Pip install sendgrid
